[package]
name = "biliTicker-gt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.12", features = ["blocking", "json"]}
serde = "1.0"
serde_json = "1.0"
ddddocr = { git = "https://github.com/Amorter/ddddocr.git", branch = "master" }
image = "0.25"